# Generated by Django 3.0.6 on 2020-12-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('dept', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
